export const BOXES = [
  {
    id: 1,
    slug:        'douceur-coreenne',
    name:        'Douceur Coréenne',
    skinType:    'sensible',
    skinLabel:   'Peau sensible',
    tag:         'Peau sensible · Réactive · Rougeurs',
    img:         '/images/peau-sensible.jpg',
    accroche:    'Apaiser et réparer sans agresser',
    description: 'Pour les peaux qui réagissent au moindre produit. Cette box K-Beauty mise sur les ingrédients les plus doux de la cosmétique coréenne — Centella, Aloe et Acide Hyaluronique — pour restaurer le confort cutané.',
    objectifs:   ['Apaiser', 'Hydrater', 'Renforcer la barrière'],
    inclus:      { always: ['Accessoires offerts', 'Fiche routine personnalisée', 'Suivi WhatsApp 1 mois', 'Livraison partout au Maroc'] },
    products: [
      {
        num:    '01',
        name:   'Nettoyant Centella Asiatica',
        img:    '/images/acc-brosse.jpg',
        desc:   'Un nettoyant ultra-doux formulé à base de Centella Asiatica pour nettoyer sans perturber le film hydrolipidique. Convient aux peaux les plus sensibles.',
        benefits: ['Nettoie sans irriter', 'Préserve le microbiome cutané', 'Effet apaisant immédiat', 'pH respectueux de la peau'],
        reverse: false,
      },
      {
        num:    '02',
        name:   'Toner Aloe Vera Calmant',
        img:    '/images/acc-bandeau.jpg',
        desc:   'Un toner à l\'Aloe Vera pur qui hydrate et apaise après le nettoyage. Sa texture légère pénètre instantanément sans résidu.',
        benefits: ['Hydratation immédiate', 'Réduit les rougeurs', 'Prépare la peau aux soins suivants', 'Sans alcool'],
        reverse: true,
      },
    ],
    why: {
      title:  'Pourquoi la Douceur Coréenne ?',
      intro:  'Les peaux sensibles se retrouvent souvent agressées par des produits trop actifs. La K-Beauty a développé une approche unique : des formules ultra-douces mais efficaces.',
      points: [
        { num: '01', title: 'Ingrédients certifiés doux',       desc: 'La Centella Asiatica est cliniquement prouvée pour réduire l\'inflammation sans effets secondaires.' },
        { num: '02', title: 'Routine minimale mais complète',    desc: 'Nettoyer, apaiser, hydrater. Pas plus. Moins de produits = moins de risque de réaction.' },
        { num: '03', title: 'Résultats visibles dès 2 semaines', desc: 'La peau se calme progressivement et gagne en confort. Moins de rougeurs, moins de tiraillements.' },
      ],
      img: '/images/peau-grasse.jpg',
    },
    testimonials: [
      { text: '"Ma peau était toujours rouge et irritée. Après 3 semaines avec cette box, les rougeurs ont vraiment diminué. Le nettoyant est devenu mon indispensable !"', name: 'Fatima R.', meta: 'Peau sensible · Casablanca' },
      { text: '"J\'avais peur d\'essayer de nouveaux produits. Mais là c\'est doux, ça fait exactement ce que ça promet."', name: 'Amira L.', meta: 'Peau réactive · Rabat' },
      { text: '"Le suivi m\'a aidée à comprendre l\'ordre d\'application. Super réactives, vraiment !"', name: 'Kenza M.', meta: 'Peau sensible · Marrakech' },
    ],
    waMessage: 'Bonjour, je suis intéressée par la Box Douceur Coréenne et j\'aimerais un conseil personnalisé',
  },
  {
    id: 2,
    slug:        'glow-intense',
    name:        'Glow Intense',
    skinType:    'terne',
    skinLabel:   'Peau terne',
    tag:         'Peau terne · Manque d\'éclat · Taches',
    img:         '/images/peau-terne.jpg',
    accroche:    'Révéler l\'éclat naturel de votre peau',
    description: 'Pour les peaux qui ont perdu leur luminosité. Cette box associe la vitamine C, la niacinamide et un SPF pour traiter les taches, unifier le teint et protéger les résultats obtenus.',
    objectifs:   ['Éclaircir', 'Unifier', 'Protéger'],
    inclus:      { always: ['Accessoires offerts', 'Fiche routine personnalisée', 'Suivi WhatsApp 1 mois', 'Livraison partout au Maroc'] },
    products: [
      {
        num:    '01',
        name:   'Huile Double Nettoyante',
        img:    '/images/acc-gua-sha.jpg',
        desc:   'La première étape du double-nettoyage coréen. Dissout le maquillage, le SPF et les impuretés lipophiles sans dessécher.',
        benefits: ['Double nettoyage coréen', 'Élimine maquillage et SPF', 'Nourrit pendant le nettoyage', 'Peau douce après rinçage'],
        reverse: false,
      },
      {
        num:    '02',
        name:   'Sérum Niacinamide 10%',
        img:    '/images/acc-ice-roller.jpg',
        desc:   'La niacinamide à 10% pour unifier le teint, réduire les pores et traiter les taches progressivement. L\'ingrédient le plus étudié en cosmétique coréenne.',
        benefits: ['Réduit les taches visibles en 4 semaines', 'Resserre les pores', 'Illumine le teint', 'Régule le sébum'],
        reverse: true,
      },
    ],
    why: {
      title:  'Pourquoi la Glow Intense ?',
      intro:  'Un teint terne s\'explique par l\'accumulation de cellules mortes, le manque d\'hydratation et l\'absence de protection SPF. Cette box attaque les 3 fronts simultanément.',
      points: [
        { num: '01', title: 'Exfolier intelligemment', desc: 'L\'huile double nettoyante et l\'essence vitamine C renouvellent le teint sans agression.' },
        { num: '02', title: 'Traiter avec précision',  desc: 'La niacinamide 10% est la concentration optimale pour des résultats visibles sans irritation.' },
        { num: '03', title: 'Protéger les résultats',  desc: 'Inutile de traiter sans SPF. La crème de jour protège et amplifie l\'effet des actifs.' },
      ],
      img: '/images/peau-sensible.jpg',
    },
    testimonials: [
      { text: '"Mon teint était vraiment terne et uniforme. En un mois, mes collègues m\'ont demandé ce que j\'avais changé !"', name: 'Sofia B.', meta: 'Peau terne · Casablanca' },
      { text: '"La niacinamide a transformé mes pores. Je n\'utilisais plus rien depuis un an, et là je suis re-conquise par les soins."', name: 'Leila A.', meta: 'Teint irrégulier · Fès' },
      { text: '"Simple, efficace. J\'ai enfin compris pourquoi le SPF est indispensable grâce à la fiche routine."', name: 'Yasmine D.', meta: 'Peau terne · Tanger' },
    ],
    waMessage: 'Bonjour, je suis intéressée par la Box Glow Intense et j\'aimerais un conseil personnalisé',
  },
  {
    id: 3,
    slug:        'equilibre-purete',
    name:        'Équilibre & Pureté',
    skinType:    'grasse',
    skinLabel:   'Peau grasse / mixte',
    tag:         'Peau grasse · Peau mixte · Imperfections',
    img:         '/images/peau-grasse.jpg',
    accroche:    'Nettoyer en profondeur sans abîmer ta peau',
    description: 'Pour les peaux mixtes à grasses avec pores visibles et imperfections. Purifie sans agresser, rééquilibre sans assécher. La box qui corrige les erreurs de soin les plus courantes.',
    objectifs:   ['Nettoyer', 'Purifier', 'Rééquilibrer'],
    inclus:      { always: ['Accessoires offerts', 'Fiche routine personnalisée', 'Suivi WhatsApp 1 mois', 'Livraison partout au Maroc'] },
    products: [
      {
        num:    '01',
        name:   'Skin1004 Centella Poremizing Clay Stick Mask',
        img:    '/images/acc-brosse.jpg',
        desc:   'Un masque purifiant en format stick innovant, enrichi en Centella Asiatica — l\'ingrédient star de la K-Beauty pour les peaux sensibilisées et grasses.',
        benefits: ['Nettoie les pores en profondeur sans agresser', 'Absorbe l\'excès de sébum durablement', 'Apaise les rougeurs grâce à la Centella', 'Format pratique — application précise et sans gâchis'],
        reverse: false,
      },
      {
        num:    '02',
        name:   'Dr. Althea 147 Crème hydratante',
        img:    '/images/acc-bandeau.jpg',
        desc:   'Une crème légère et apaisante formulée pour restaurer l\'équilibre de la peau après la purification. Texture gel-crème qui fond sur la peau sans effet gras.',
        benefits: ['Hydrate sans alourdir — idéale peaux mixtes', 'Répare la barrière cutanée fragilisée', 'Apaise les irritations post-nettoyage', 'Absorption rapide — finish mat naturel'],
        reverse: true,
      },
    ],
    why: {
      title:  'Pourquoi la Équilibre & Pureté ?',
      intro:  'Les peaux grasses et mixtes ont souvent les mêmes erreurs : trop nettoyer, trop assécher, et finalement aggraver la situation. Cette box corrige ça.',
      points: [
        { num: '01', title: 'Purifier sans agresser',         desc: 'La Centella Asiatica nettoie les pores et calme l\'inflammation simultanément — pas l\'un sans l\'autre.' },
        { num: '02', title: 'Rééquilibrer durablement',        desc: 'Un nettoyage trop intense provoque une surproduction de sébum. La crème Dr. Althea évite cet effet rebond.' },
        { num: '03', title: 'Routine en 2 étapes simples',     desc: 'Pas besoin de 10 produits. Cette box te donne l\'essentiel pour voir des résultats dès 2 semaines.' },
      ],
      img: '/images/peau-sensible.jpg',
    },
    testimonials: [
      { text: '"J\'avais des pores très visibles et un excès de sébum permanent. Après 3 semaines, mes pores ont visiblement diminué et ma peau brille beaucoup moins."', name: 'Sara M.', meta: 'Peau mixte · Casablanca' },
      { text: '"J\'avais peur que les produits asséchent ma peau. Mais la crème Dr. Althea est parfaite — légère, sans effet gras. Ma peau est enfin équilibrée."', name: 'Nadia B.', meta: 'Peau grasse · Rabat' },
      { text: '"Le suivi était incroyable. J\'ai eu une réponse détaillée en moins d\'une heure. On sent vraiment qu\'elles connaissent leurs produits."', name: 'Imane K.', meta: 'Peau mixte · Marrakech' },
    ],
    waMessage: 'Bonjour, je suis intéressée par la Box Équilibre & Pureté et j\'aimerais un conseil personnalisé',
  },
  {
    id: 4,
    slug:        'hydra-boost',
    name:        'Hydra Boost',
    skinType:    'seche',
    skinLabel:   'Peau sèche',
    tag:         'Peau sèche · Tiraillements · Déshydratation',
    img:         '/images/peau-seche.jpg',
    accroche:    'Nourrir et repulper les peaux déshydratées',
    description: 'Pour les peaux qui tirent constamment et manquent d\'eau. Cette box associe l\'escargot réparateur, les céramides reconstituants et une crème 72h pour une hydratation profonde et durable.',
    objectifs:   ['Nourrir', 'Réparer', 'Hydrater 72h'],
    inclus:      { always: ['Accessoires offerts', 'Fiche routine personnalisée', 'Suivi WhatsApp 1 mois', 'Livraison partout au Maroc'] },
    products: [
      {
        num:    '01',
        name:   'Lait Nettoyant Doux',
        img:    '/images/acc-rouleau-jade.jpg',
        desc:   'Un lait nettoyant crémeux qui nettoie sans retirer le film hydrolipidique. Idéal pour les peaux sèches qui souffrent des nettoyants classiques.',
        benefits: ['Nettoie sans dessécher', 'Laisse un film protecteur', 'Odeur délicate', 'Rincé ou essuyé au gant'],
        reverse: false,
      },
      {
        num:    '02',
        name:   'Sérum Céramides & Snail',
        img:    '/images/acc-eponge.jpg',
        desc:   'Un sérum double action : les céramides reconstituent la barrière cutanée, la bave d\'escargot répare et repulpe. Le duo star pour les peaux sèches.',
        benefits: ['Barrière cutanée renforcée en 7 jours', 'Effet repulpant visible', 'Cicatrisation des micro-lésions', 'Texture sérum légère'],
        reverse: true,
      },
    ],
    why: {
      title:  'Pourquoi la Hydra Boost ?',
      intro:  'La déshydratation n\'est pas une fatalité. Avec les bons actifs, une peau sèche peut retrouver du confort et de la souplesse en quelques semaines.',
      points: [
        { num: '01', title: 'Nettoyer sans agresser',  desc: 'Un lait nettoyant respecte le film hydrolipidique, contrairement aux gels moussants classiques.' },
        { num: '02', title: 'Réparer en profondeur',   desc: 'Les céramides sont les briques naturelles de la peau. Les reconstituer, c\'est réparer durablement.' },
        { num: '03', title: 'Verrouiller l\'hydratation', desc: 'La crème 72h agit comme un film protecteur qui empêche l\'eau de s\'évaporer.' },
      ],
      img: '/images/peau-sensible.jpg',
    },
    testimonials: [
      { text: '"Mes tiraillements ont disparu en 10 jours. Je n\'avais jamais trouvé une crème qui tienne aussi bien l\'hydratation."', name: 'Houda M.', meta: 'Peau sèche · Agadir' },
      { text: '"La bave d\'escargot m\'a convaincue. Ma peau est beaucoup plus douce et lumineuse."', name: 'Asmae R.', meta: 'Peau déshydratée · Casablanca' },
      { text: '"Le suivi m\'a aidée à comprendre pourquoi je devais appliquer le sérum avant la crème. Ça change tout !"', name: 'Zineb L.', meta: 'Peau sèche · Rabat' },
    ],
    waMessage: 'Bonjour, je suis intéressée par la Box Hydra Boost et j\'aimerais un conseil personnalisé',
  },
  {
    id: 5,
    slug:        'zone-t-maitrisee',
    name:        'Zone T Maîtrisée',
    skinType:    'mixte',
    skinLabel:   'Peau mixte',
    tag:         'Peau mixte · Zone T · Déséquilibre',
    img:         '/images/box-mixte.jpg',
    accroche:    'Équilibrer sans sacrifier les joues sèches',
    description: 'La peau mixte est la plus complexe à traiter — brillance sur la zone T, sécheresse sur les joues. Cette box bi-phase traite chaque zone selon ses besoins.',
    objectifs:   ['Équilibrer', 'Matifier', 'Cibler'],
    inclus:      { always: ['Accessoires offerts', 'Fiche routine personnalisée', 'Suivi WhatsApp 1 mois', 'Livraison partout au Maroc'] },
    products: [
      {
        num:    '01',
        name:   'Gel Nettoyant Équilibrant',
        img:    '/images/acc-brosse.jpg',
        desc:   'Un gel nettoyant bi-fonction qui élimine l\'excès de sébum sur la zone T tout en respectant les joues. La routine commence toujours bien.',
        benefits: ['Nettoie la zone T sans assécher les joues', 'Texture mousse légère', 'Contrôle sébum durable 8h', 'Peaux mixtes et normales'],
        reverse: false,
      },
      {
        num:    '02',
        name:   'Toner Bi-Phase Rééquilibrant',
        img:    '/images/acc-gua-sha.jpg',
        desc:   'Un toner innovant en deux phases qui s\'adapte selon la zone d\'application. Phase aqueuse pour hydrater les joues, phase huileuse pour purifier la zone T.',
        benefits: ['Technologie bi-phase unique', 'Adapté zone par zone', 'Rééquilibre en une application', 'Agiter avant utilisation'],
        reverse: true,
      },
    ],
    why: {
      title:  'Pourquoi la Zone T Maîtrisée ?',
      intro:  'La plupart des routines sont formulées pour un seul type de peau. La peau mixte mérite des produits qui comprennent sa complexité.',
      points: [
        { num: '01', title: 'Traiter zone par zone',         desc: 'Appliquer la même chose partout, c\'est l\'erreur classique. Cette box vous apprend à différencier.' },
        { num: '02', title: 'Matifier sans assécher',         desc: 'Le gel équilibrant contrôle le sébum sans déclencher de compensation sèche sur les joues.' },
        { num: '03', title: 'Équilibre visible en 3 semaines', desc: 'Les premières semaines sont décisives. La fiche routine vous guide jour par jour.' },
      ],
      img: '/images/peau-sensible.jpg',
    },
    testimonials: [
      { text: '"J\'utilisais deux routines différentes pour zone T et joues. Maintenant, cette box m\'a simplifié la vie !"', name: 'Meriem O.', meta: 'Peau mixte · Casablanca' },
      { text: '"Le toner bi-phase est génial. Je n\'avais jamais vu ça. Vraiment efficace sur ma zone T."', name: 'Chaïma B.', meta: 'Peau mixte · Tanger' },
      { text: '"Simple et logique. La fiche routine explique très bien quoi mettre où. Je recommande !"', name: 'Rania S.', meta: 'Peau mixte · Fès' },
    ],
    waMessage: 'Bonjour, je suis intéressée par la Box Zone T Maîtrisée et j\'aimerais un conseil personnalisé',
  },
  {
    id: 6,
    slug:        'youth-elixir',
    name:        'Youth Élixir',
    skinType:    'anti-age',
    skinLabel:   'Anti-âge',
    tag:         'Anti-âge · Prévention · Fermeté',
    img:         '/images/box-antiage.jpg',
    accroche:    'Prévenir et corriger les premiers signes du temps',
    description: 'Pour les peaux qui souhaitent anticiper ou corriger les premiers signes de l\'âge. Cette box K-Beauty associe rétinol doux, peptides et collagène pour une action anti-âge globale.',
    objectifs:   ['Prévenir', 'Corriger', 'Raffermir'],
    inclus:      { always: ['Accessoires offerts', 'Fiche routine personnalisée', 'Suivi WhatsApp 1 mois', 'Livraison partout au Maroc'] },
    products: [
      {
        num:    '01',
        name:   'Sérum Rétinol + Peptides',
        img:    '/images/acc-ice-roller.jpg',
        desc:   'Un sérum nouvelle génération qui combine rétinol doux (0.1%) et peptides de soin. Efficace sans les irritations du rétinol classique.',
        benefits: ['Réduit les ridules dès 6 semaines', 'Rétinol encapsulé — tolérance maximale', 'Peptides stimulant le collagène', 'Utilisation soir uniquement'],
        reverse: false,
      },
      {
        num:    '02',
        name:   'Crème Collagène & Contour Yeux',
        img:    '/images/acc-rouleau-jade.jpg',
        desc:   'Une crème riche en collagène marin et en caféine pour le contour des yeux. Combat les poches, les cernes et les pattes d\'oie.',
        benefits: ['Raffermit la peau visible', 'Dégonfle les poches le matin', 'Réduit les cernes progressivement', 'Texture légère non comédogène'],
        reverse: true,
      },
    ],
    why: {
      title:  'Pourquoi la Youth Élixir ?',
      intro:  'Prévenir vaut toujours mieux que corriger. Les actifs anti-âge de la K-Beauty sont plus doux et plus progressifs que leurs équivalents occidentaux.',
      points: [
        { num: '01', title: 'Rétinol sans les effets secondaires', desc: 'Le rétinol encapsulé libère l\'actif progressivement. Résultats comparables, tolérance bien meilleure.' },
        { num: '02', title: 'Stimuler le collagène naturellement',  desc: 'Les peptides signalent à la peau de produire son propre collagène — l\'approche la plus durable.' },
        { num: '03', title: 'Commencer tôt, conserver longtemps',   desc: 'La prévention anti-âge dès 25 ans donne des résultats incomparablement meilleurs qu\'une correction tardive.' },
      ],
      img: '/images/peau-sensible.jpg',
    },
    testimonials: [
      { text: '"J\'avais peur du rétinol après une mauvaise expérience. Celui-là est doux, ma peau ne pèle pas du tout."', name: 'Widad H.', meta: 'Anti-âge · Casablanca' },
      { text: '"Les pattes d\'oie ont visiblement diminué en 6 semaines. Je suis bluffée par les résultats."', name: 'Loubna A.', meta: 'Prévention rides · Rabat' },
      { text: '"Le contour yeux est ma révélation. Plus de poches le matin, c\'est un miracle !"', name: 'Najat B.', meta: 'Anti-âge · Marrakech' },
    ],
    waMessage: 'Bonjour, je suis intéressée par la Box Youth Élixir et j\'aimerais un conseil personnalisé',
  },
]

export const PRODUCTS = [
  {
    id: 1,
    slug:     'ice-roller-visage',
    img:      '/images/acc-ice-roller.jpg',
    cat:      'soin',
    catLabel: 'Soin du visage',
    name:     'Ice Roller Visage',
    tagline:  'Le secret des coréennes pour un teint parfait le matin',
    desc:     'Dégonfle, resserre les pores et donne un éclat immédiat en 5 minutes.',
    descLong: 'L\'ice roller est l\'outil de massage froid qui révolutionne la routine beauté coréenne. En faisant rouler l\'embout glacé sur votre visage, vous activez la microcirculation, dégonflez les zones gonflées et ressortez les pores. Résultat : un teint frais et lumineux en 5 minutes chrono.',
    price:    89,
    oldPrice: null,
    rating:   4.9,
    reviews:  48,
    badge:    null,
    stock:    'ok',
    stockLabel: 'En stock',
    benefits: ['Réduit les rougeurs', 'Resserre les pores', 'Éclat immédiat'],
    howTo: ['Mettre au congélateur 2h avant utilisation', 'Rouler en mouvements vers le haut et vers l\'extérieur', '5 à 10 minutes le matin', 'Nettoyer l\'embout après chaque usage'],
    details: [
      { label: 'Matière', value: 'Embout gel médical, poignée ABS' },
      { label: 'Utilisation', value: 'Visage, cou, décolleté' },
      { label: 'Fréquence', value: 'Quotidienne' },
      { label: 'Conservation', value: 'Congélateur ou réfrigérateur' },
    ],
    related: [2, 4],
  },
  {
    id: 2,
    slug:     'gua-sha-quartz-rose',
    img:      '/images/acc-gua-sha.jpg',
    cat:      'massage',
    catLabel: 'Massage & drainage',
    name:     'Gua Sha Quartz Rose',
    tagline:  'Le lifting naturel ancestral revisité par la K-Beauty',
    desc:     'Drainage lymphatique, sculpture du visage et effet lifting naturel.',
    descLong: 'Le Gua Sha en quartz rose est l\'outil de massage ancestral remis au goût du jour par la beauté coréenne. Sa pierre naturelle reste fraîche au toucher et ses bords biseautés s\'adaptent parfaitement aux contours du visage pour un drainage optimal et un effet lifting immédiat.',
    price:    129,
    oldPrice: null,
    rating:   4.8,
    reviews:  35,
    badge:    'popular',
    stock:    'ok',
    stockLabel: 'En stock',
    benefits: ['Drainage lymphatique', 'Lifting naturel', 'Anti-tension'],
    howTo: ['Appliquer une huile ou un sérum avant usage', 'Maintenir à 15° par rapport à la peau', 'Mouvements de bas en haut, toujours vers les ganglions', '5 minutes par côté'],
    details: [
      { label: 'Matière', value: 'Quartz rose naturel 100%' },
      { label: 'Dimensions', value: '8 × 5 cm' },
      { label: 'Fréquence', value: '3 à 5 fois par semaine' },
      { label: 'Entretien', value: 'Rincer à l\'eau froide après usage' },
    ],
    related: [1, 4],
  },
  {
    id: 3,
    slug:     'bandeau-skincare',
    img:      '/images/acc-bandeau.jpg',
    cat:      'routine',
    catLabel: 'Accessoires routine',
    name:     'Bandeau Skincare',
    tagline:  'Le petit accessoire qui change toute la routine',
    desc:     'Maintien parfait pour vos soins visage. Microfibre douce, lavable et réutilisable.',
    descLong: 'Un accessoire indispensable souvent oublié : le bandeau maintient les cheveux hors du visage pendant toute votre routine, évite que vos produits ne s\'accrochent aux cheveux et garantit une application précise. En microfibre ultra-douce, il est lavable et réutilisable à l\'infini.',
    price:    45,
    oldPrice: null,
    rating:   4.7,
    reviews:  22,
    badge:    'new',
    stock:    'ok',
    stockLabel: 'En stock',
    benefits: ['Réutilisable', 'Ultra doux', 'Lavable'],
    howTo: ['Enfiler le bandeau avant tout soin', 'Laver en machine à 30°C', 'Séchage à plat recommandé', 'Remplacer tous les 6 mois'],
    details: [
      { label: 'Matière', value: 'Microfibre 80% polyester, 20% élasthanne' },
      { label: 'Couleur', value: 'Rose poudré / Blanc / Beige' },
      { label: 'Lavage', value: 'Machine 30°C, sac filet' },
      { label: 'Taille', value: 'Taille unique, élastique réglable' },
    ],
    related: [4, 6],
  },
  {
    id: 4,
    slug:     'brosse-nettoyante-silicone',
    img:      '/images/acc-brosse.jpg',
    cat:      'nettoyage',
    catLabel: 'Nettoyage',
    name:     'Brosse Nettoyante Silicone',
    tagline:  'Le nettoyage 3x plus efficace qu\'avec les mains',
    desc:     'Nettoyage en profondeur ultra doux. Élimine les impuretés sans agresser la peau.',
    descLong: 'La brosse nettoyante en silicone révolutionne le nettoyage du visage. Ses micro-picots en silicone médical créent une légère friction qui décolle les impuretés logées dans les pores tout en effectuant un micro-massage stimulant. Hygiénique et anti-bactérienne par nature.',
    price:    159,
    oldPrice: null,
    rating:   4.9,
    reviews:  61,
    badge:    null,
    stock:    'low',
    stockLabel: 'Stock limité',
    benefits: ['Nettoyage profond', 'Ultra doux', 'Anti-bactérien'],
    howTo: ['Mouiller la peau et la brosse', 'Appliquer le nettoyant sur la brosse ou le visage', 'Masser en cercles pendant 60 secondes', 'Rincer à l\'eau tiède, sécher la brosse'],
    details: [
      { label: 'Matière', value: 'Silicone médical grade A' },
      { label: 'Entretien', value: 'Rincer après usage, sécher à l\'air libre' },
      { label: 'Fréquence', value: '1 à 2 fois par jour' },
      { label: 'Compatibilité', value: 'Tous types de peau' },
    ],
    related: [3, 6],
  },
  {
    id: 5,
    slug:     'rouleau-jade-double-tete',
    img:      '/images/acc-rouleau-jade.jpg',
    cat:      'massage',
    catLabel: 'Massage & drainage',
    name:     'Rouleau Jade Double Tête',
    tagline:  'Grand visage + petit contour — un seul outil',
    desc:     'Double tête pour grand et petit contour. Drainage, anti-poches et éclat du teint.',
    descLong: 'Le rouleau jade à double tête est l\'outil de massage coréen le plus polyvalent. La grande tête traite les joues, le front et le cou en longs mouvements drainants. La petite tête s\'occupe précisément du contour des yeux, des ailes du nez et des lèvres. Un seul outil pour tout le visage.',
    price:    99,
    oldPrice: 120,
    rating:   4.6,
    reviews:  35,
    badge:    'promo',
    stock:    'ok',
    stockLabel: 'En stock',
    benefits: ['Anti-poches', 'Éclat', 'Double usage'],
    howTo: ['Utiliser sur peau propre après sérum', 'Grande tête : joues, front, cou vers le haut', 'Petite tête : contour des yeux de l\'intérieur vers l\'extérieur', 'Conserver au réfrigérateur pour effet décongestionnant'],
    details: [
      { label: 'Matière', value: 'Jade naturel, monture métal doré' },
      { label: 'Têtes', value: 'Grande (4cm) + petite (2cm)' },
      { label: 'Poids', value: 'Environ 85g' },
      { label: 'Entretien', value: 'Rincer et sécher après usage' },
    ],
    related: [2, 1],
  },
  {
    id: 6,
    slug:     'eponge-konjac',
    img:      '/images/acc-eponge.jpg',
    cat:      'nettoyage',
    catLabel: 'Nettoyage',
    name:     'Éponge Konjac',
    tagline:  'L\'exfoliation la plus douce qui existe — 100% naturelle',
    desc:     'Exfoliation douce naturelle, 100% végétale. Idéale pour les peaux sensibles.',
    descLong: 'L\'éponge Konjac est fabriquée à partir de la racine de konjac, une plante asiatique. Sa texture naturellement douce exfolie sans abimer, nettoie sans agresser et masse en douceur. Elle est 100% végétale, biodégradable et idéale même pour les peaux les plus sensibles.',
    price:    55,
    oldPrice: 69,
    rating:   4.8,
    reviews:  29,
    badge:    'promo',
    stock:    'ok',
    stockLabel: 'En stock',
    benefits: ['100% naturel', 'Exfoliant doux', 'Vegan'],
    howTo: ['Mouiller abondamment avant usage', 'Appliquer sur peau nettoyée ou avec nettoyant', 'Masser en cercles pendant 1 à 2 minutes', 'Rincer et essorer après usage, sécher à l\'air libre'],
    details: [
      { label: 'Composition', value: '100% fibre de Konjac naturelle' },
      { label: 'Durée de vie', value: '2 à 3 mois selon usage' },
      { label: 'Certifications', value: 'Vegan, biodégradable' },
      { label: 'Fréquence', value: '3 à 4 fois par semaine maximum' },
    ],
    related: [4, 3],
  },
]
