import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ args: ['--no-sandbox','--disable-setuid-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle2', timeout: 15000 });
await new Promise(r => setTimeout(r, 2500));
await page.screenshot({ path: 'screen-desktop.png' });
await page.setViewport({ width: 390, height: 844 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle2', timeout: 10000 });
await new Promise(r => setTimeout(r, 1500));
await page.screenshot({ path: 'screen-mobile.png' });
await browser.close();
console.log('OK');
